### ISSUE TITLE
Chris Audit Fixes

### ISSUE THREAD

**Issue by 134dd3v** [RageTrade/core#108]
## PRs involved in audix fixes

- [https://github.com/rage-trade/perpswap-contracts/pull/92](https://github.com/rage-trade/perpswap-contracts/pull/92)
- [https://github.com/rage-trade/perpswap-contracts/pull/93](https://github.com/rage-trade/perpswap-contracts/pull/93)
- [https://github.com/rage-trade/perpswap-contracts/pull/99](https://github.com/rage-trade/perpswap-contracts/pull/99)

## Issues

(Please only look at the ticked ones for now, the rest ones will be confirmed ASAP)

- [x]  3.1 poolwrapper external function checks (fixed, PR#92, 1f9d87008260e5014ec8017e924a4b966bcc1c1e)
- [x]  3.2 Trader Position Increase issue (fixed, PR#93, 5c1d41949a815e19b8402ccbfbbf6fc5720f1427, 0e188a58ee24a3bb4bf574167f649ccafcdb546c)
- [x]  3.3 Fix exclude (fixed, PR#99, 4587ac2ecea265ac44acbf5eecf7b190e16aa15a)
- [x]  3.4 Calldata.limit (fixed, PR#92, 188be912508823b770a242e6d376c697b1222c47)
- [x]  3.5 Unsafe casting @Alex (fixed, PR#99, e793cbe8e6c21471ffc16594385a18465f2df308)
- [x]  3.6 Reduce issue (file removed, PR#93, 1a08c638f42321c69c8c0c03cee0fc1b1e364663)
- [x]  3.7 Exclude issue (file removed, PR#93, 1a08c638f42321c69c8c0c03cee0fc1b1e364663)
- [x]  3.8 Extsload - fix memory corruption? (fixed, PR#92, c5d7e41e825fd68b68d1645be7ba0f8e682eb111)
- [x]  3.9 VTokenPosition deactivation logic (fixed, PR#93, bd8999fe4688cc25a6c21286abc37bc544e09ea2)
- [x]  3.10 Increase oracle cardinality in rage trade factory. (fixed, PR#93, b5a490699fb39fd551616ddeb833795601a8b621)
- [x]  3.11 Unsupported RToken withdrawal - c36a2fb0b9c7744f010219227b03507ac7a74c36
- [x]  3.12 - No Fix Needed
- [x]  3.13 - Permissionless removal of limit orders. Issue fixed - Limit order removal should use currentTick rather than twapTick to check if order is filled. Removal of limit order away from TWAP price (if current price is far away due to flash attack) would not be an issue since token value on removal would be higher ( https://docs.google.com/spreadsheets/d/16Q3FP7NjmRmNUwwuQNt3D3aiW91dDBDj/edit?usp=sharing&ouid=101320775168527941295&rtpof=true&sd=true ). (PR#93, d3d829992bacd35a249c60b4d7420972c19f4507, df442ddf64eda238cff2eeebc5477a63e458e175, 667f30ee1b11ccb8e7679f4d6d4578254cd0d355). The commit : df442ddf64eda238cff2eeebc5477a63e458e175 introduced an issue which has been fixed with the commit: 7ed75a479af8e5527267d5c78d3a043ebee7e296.
- [x]  3.14 - SignedFullMath issue (fixed, PR#92, 8e11dff350795435e00294e0cb708886cf7b07f5)
- [x]  3.15 - Real Token Never init - real token initialized not needed anymore - have removed it (fixed, PR#93, 5d407612f44244a22ee02fb47aef600517937d23)
- [x]  3.16 - getLiquidityPosition optimization (fixed, PR#93, b2c51e04cf6af76c53d146f7182624766da82f65)
- [x]  3.17 - Include efficiency issue 1a08c638f42321c69c8c0c03cee0fc1b1e364663 (File Removed)
- [x]  3.18 - Misc
    - [x]  Account.LiquidationParams: The fixFee and minRequiredMargin variables do not exist on the
    struct anymore but are still listed in the docs. 308e9abe61eeac43d25be64a878ff638c2fc914e
    - [x]  Account.liquidateLiquidityPositions: The protocol.liquidationParams.liquidationFeeFraction
    is divided by 1e5 whereas all other Account.LiquidationParams are in basis points (1e4).
    Document the dierent base for all of these parameters and consider changing all percentages
    to a common base. 308e9abe61eeac43d25be64a878ff638c2fc914e
    - [x]  Account.getLiquidationPriceX128AndFee: The parameter descriptions in the docs do not match
    the parameters 308e9abe61eeac43d25be64a878ff638c2fc914e
    - [x]  Account.updateLiquidationAccounts: Function uses anamedreturn variable liquidatorBalanceAdjustments
    but never sets it. The last balanceAdjustments assignment should be to liquidatorBalanceAdjustments 
    instead (and the return statement should be skipped). 308e9abe61eeac43d25be64a878ff638c2fc914e
    - [x]  Uint32L8Set._existsReducer: Function not used. (file removed, PR#93, 1a08c638f42321c69c8c0c03cee0fc1b1e364663)
    - [x]  Uint48Lib.concat: No need to mask the 24 lower bits on the 24-bit val2 value with and(val2, 0
    x000000ffffff). One can directly use the 24-bits of val2. (NO ACTION)
    - [x]  ClearingHouseStorage.realTokenInitilized / ClearingHouseView.isRealTokenAlreadyInitilized
    : TYPO: Initilized -> Initialized 5d407612f44244a22ee02fb47aef600517937d23 (Functions removed)
    - [x]  ClearingHouse: The *WithGasClaim functions are not part of the IClearingHouse interface. 800623fc2a4019c506348ff5acf4e357523000ea
    - [x]  ClearingHouseEthereum: The TODO put a upper limit to tx.gasprice seems to already be resolved by use of the checkTxGasPrice(tx.gasprice) modifier. (NO ACTION)
    - [x]  ClearingHouseEthereum: EVM gas costs can change over time with new forks. (NO ACTION)
    - [x]  VBaseDeployer._isVBaseAddressGood: comment should say “most significant hex char of address
    is "f"” instead of “d”. (fixed, PR#93, e2710a1439896eb36319364b2a1156333118ba44)
    - [x]  VPoolWrapper.swap: Regarding the TODO questioning if the assert(vTokenIn_simulated ==
    vTokenIn && vBaseIn_simulated == vBaseIn) should be removed: This invariant should always
    be true, so we recommend keeping it to be able to easier detect any issues. (NO ACTION)
    - [x]  Tick.getUniswapFeeGrowthInside: This function is not used and should be removed. (fixed, PR#93, 801deed2d4787ccc7f652d3079267067ab390af5)
